name: namico_db_wrapper
description: A Wrapper around sqlite3 with encryption support.
version: 4.1.0
repository: https://github.com/namidaco/namico_db_wrapper

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  sqlite3: ^2.4.3
  sqlcipher_flutter_libs: ^0.6.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  benchmarking: ^0.6.1
